# Site settings
title: Yu-Feng's Learning Notes
email: 
description: ""
baseurl: ""
url: "http://FrankYFHsu.github.io"
github_username:  FrankYFHsu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
